### ISSUE TITLE
Overwriting URLs

### ISSUE THREAD

**Issue by caycaycarly** [raftario/filite#12]
Right now, when a user inputs a URL which is already in use, the input box has a yellow outline to express that the URL is in use. The user can go ahead with the action, and his new request overwrites the content was submitted previously using that URL.

This behavior makes sense when filite is used by an individual or in a group with common interests. But, when filite is used publicly, this poses a BIG issue. Because, anyone can hijack the URL of another person.

What's the best way to fix this issue?

- Disable overwriting for filite (globally, via config file)
- Checkbox to disable overwriting while creating a URL

**Comment by raftario** [comment]
I feel like the global config option would make more sense in that case, and I'd like to keep the UI as minimal as possible. So probably 2nd one.

**Comment by raftario** [comment]
The web UI will not let you overwrite existing entries anymore. However, because of the current single login nature of the tool, it is possible to delete any entry and a config option to disable overwrites wouldn't be very useful.
