### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by steven-joruk** [raftario/filite#14]
When I acces `/logout` I see the "Logged out" text, and I added a debug check to make sure `identity.is_none()` at that point, which it is... but then when I access any other page it's somehow remembered the identity. I tried this with Firefox and Gnome Web. I don't have any cookies stored:

```
[2019-10-26T12:19:49Z INFO  actix_web::middleware::logger] [::1]:34458 "GET /logout HTTP/1.1" 200 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15
(KHTML, like Gecko) Version/13.0 Safari/605.1.15 Epiphany/605.1.15" 0.000530

Go to '/'
**snip favico**

[2019-10-26T12:19:52Z INFO  actix_web::middleware::logger] [::1]:34458 "GET / HTTP/1.1" 200 13041 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (K
HTML, like Gecko) Version/13.0 Safari/605.1.15 Epiphany/605.1.15" 0.000617
identity: filite
```

**Comment by raftario** [comment]
I assumed this was due to Firefox saving the credentials, once I disabled it logout was working fine, but since the identity isn't None this obviously isn't the case.

**Comment by steven-joruk** [comment]
https://github.com/actix/actix-web/issues/1140

Looks like this person might be seeing the same thing.

After some investigation I think the problem isn't to do with actix-identity directly - if you unconditionally forget the session on logout like their documentation's example, the problem remains:
```
identity.forget();
HttpResponse::Ok().body("Logged out")
```

If you force it to always show the basic authentication, the identity is forgotten. You have to manually exit the login loop and go to `/` in order to see it.

I'm not sure how basic authentication affects the session state, but it's got to be related. I find it bizarre that closing and opening a private Firefox window leaves me logged in...

**Comment by steven-joruk** [comment]
Sorry, you're right. I didn't realise Firefox private windows shared the same cache, and I had a separate window private open during my testing :man_facepalming:

**Comment by the-notable** [comment]
I see this issue was closed, but was there any resolution. I having the same problem where the identity isn't being "forgotten" on logout. If I manually resend the old cookie on subsequent requests the Identity Service still has the identity. @steven-joruk
