### ISSUE TITLE
Question: How to delete an entry?

### ISSUE THREAD

**Issue by DylanVanAssche** [raftario/filite#18]
I really like your pastebin tool!
I was trying to delete an entry using the following command:
```
curl -X DELETE https://username:password@bin.example.com/t/<ID>
```
ID is the ID of the entry (`12548`) when you get the output of `https://username:password@bin.example.com/t`:
```
[
  {
    "id": 12548,
    "contents": "This is a test!",
    "created": 1573691264,
    "highlight": false
  }
]
```
I get the reply `Deleted` but the entry is still there... Is this the wrong way to delete an entry?

**Comment by raftario** [comment]
That should work, definitely sounds like a bug. Will look into it.

**Comment by raftario** [comment]
Using the same command it works for me. Have you tried force refreshing the page ?

**Comment by DylanVanAssche** [comment]
I refreshed the page by force but it's still there.
I checked the SQLite database too, the entry is still there.

Even if I submit an ID which does not exist (for example: `0` or `1`), the response is still `Deleted` instead of `Invalid ID`.

**Comment by raftario** [comment]
Found the issue. The delete statements didn't check if anything got deleted, which I just fixed. Your issue arises from the fact you're using the numerical ID, while the deletion endpoint expects the base36 string.

I'll probably rework the tool to use the strings as IDs directly instead of numbers since that has been annoying me quite a bit, but in the meantime I'll add a simple endpoint to convert numerical IDs to base36.

**Comment by raftario** [comment]
The fix and the new route are on master. You can get the base36 string from a numerical ID with `GET /id/{numerical_id}`. You'll need to reset the password using `filite passwd` when updating the binary (another stupid thing I need to fix).

**Comment by DylanVanAssche** [comment]
Works great! Thanks!

**Comment by Syndamia** [comment]
I just want to mention that I made a script for more easily browsing through all of the registered string IDs, which can really help when trying to delete a lot of entries.
https://github.com/Syndamia/filite-list/

**Comment by raftario** [comment]
@Syndamia If you want to open a PR adding a link to it in the readme on master feel free, that does look useful
