### ISSUE TITLE
Build for armhf processor?

### ISSUE THREAD

**Issue by luftaquila** [raftario/filite#19]
I tried to execute filite init, but it failed with error:
 cannot execute binary file: exec format error. My device is raspberry pi 3 with raspbian. Thank you for help.

**Comment by raftario** [comment]
The prebuilt binaries are only for x86_64. You can easily build it yourself on the Pi itself by running `cargo install filite` (you'll need the Rust toolchain installed, the easiest way to get it is [rustup](https://rustup.rs/))

**Comment by luftaquila** [comment]
> The prebuilt binaries are only for x86_64. You can easily build it yourself on the Pi itself by running `cargo install filite` (you'll need the Rust toolchain installed, the easiest way to get it is [rustup](https://rustup.rs/))

Uh, my pi just stopped working while building : ( 
I guess it was too harsh for pi to compile it. Thank you anyway.

**Comment by raftario** [comment]
Hmm, that's actually a pretty fair point. If you open a PR to enable automatic builds for the Pi I'll merge it ([here is a good starting point](https://github.com/actions-rs/cargo#cross)).

I can also add it myself, but it's not really one of my priorities so you'll have to wait for that.

**Comment by luftaquila** [comment]
@raftario Since I'm new to the GitHub Actions, I struggled to make it work with armv7 and failed :(
Filite binary is created, but it says 'cannot execute binary file: Exec format error'.
I think it doesn't compiled with armv7 toolchain but I don't know why. When you have some free time, please check mine. Thank you.

My tries : https://github.com/luftaquila/filite/actions

**Comment by raftario** [comment]
You're not uploading the right binary. The armv7 one will be in `target/armv7-unknown-linux-gnueabihf/release/`.

**Comment by raftario** [comment]
Now that I think of it, an automatic build isn't really necessary since you can also use [cross](https://github.com/rust-embedded/cross) from your desktop to build for the Pi.

**Comment by luftaquila** [comment]
Uh, I see. I'll try it. Thank you!
