### ISSUE TITLE
[Ported] Win32 Port

### ISSUE THREAD

**Issue by Malte0621** [raftario/filite#27]
I managed to port this application to a 32 bit windows application.
It took a while. But wow, it was worth it. Now i can run this on a lightweight virtual machine. Running 32 bit.

If someone else wants to download it. Just ask.. (reply).

Images:
![filite-1](https://user-images.githubusercontent.com/50240920/93721064-bd1d5c80-fb8d-11ea-99d9-1d62a57f2309.png)
![filite-2](https://user-images.githubusercontent.com/50240920/93721069-c3133d80-fb8d-11ea-8aea-3427f0b1cf19.png)
![filite-3](https://user-images.githubusercontent.com/50240920/93721073-c4dd0100-fb8d-11ea-8d17-8a40340e7ab4.png)
![filite-4](https://user-images.githubusercontent.com/50240920/93721076-c73f5b00-fb8d-11ea-966f-5720d697d6f6.png)

:D

**Comment by raftario** [comment]
Just curious since you labeled it as a port, were there any modifications to the code required for it to compile for win32 ?
