### ISSUE TITLE
URL Shortening - display the link instead of opening the shortened link in a new tab

### ISSUE THREAD

**Issue by caycaycarly** [raftario/filite#4]
When a URL is shortened the existing behavior is that the shortened URL is opened in a new tab which them immediately resolves to the original URL. The purpose of a URL shortener is to shorten a url and being able to copy the url to share it to other people. But here, a user would have to remember the custom alias that he inputted, or the random alias that was generated before hitting the submit button.

**Comment by raftario** [comment]
Yeah that annoyed me too. Adding the option to copy created links to the clipboard would also be nice. Will be looking into that one as soon as possible.
