### ISSUE TITLE
Add a reset command to generate a fresh config and/or password

### ISSUE THREAD

**Issue by caycaycarly** [raftario/filite#7]
When a user deletes the contents of the .filite/ folder, in order to start afresh, he can't generate a new config file.

The following error is displayed
```
$ ./filite.exe
Can't read config file.
```
When the .filite/ folder is deleted, the user can generate the config file again.

**Comment by raftario** [comment]
Would adding a `reset` subcommand make sense?

**Comment by caycaycarly** [comment]
Yes, that could be a fix.

`reset config` and `reset password`

**Comment by steven-joruk** [comment]
I like your idea of a reset command. The related PR just handles the case where the file has been deleted.

**Comment by raftario** [comment]
Nice, adding the command should be trivial since everything that's needed is already in the setup module. Will look at the PRs once I'm able to test them.

**Comment by raftario** [comment]
#13 fixed the original issue, keeping this open to track and discuss the reset command.

**Comment by raftario** [comment]
The command is `filite init`
