### ISSUE TITLE
UI bug in Chrome

### ISSUE THREAD

**Issue by caycaycarly** [raftario/filite#8]
All three sections of filite, i.e., "Links", "Files". and "Texts", have an additional grey bar at the bottom of the UI on Chrome. Also, the scroll bars, which are not visible on Firefox, are visible on Chrome.

![0](https://user-images.githubusercontent.com/57024945/67613696-1938fe80-f7ce-11e9-8a84-29da22a41b8c.PNG)

![1](https://user-images.githubusercontent.com/57024945/67613695-1938fe80-f7ce-11e9-89bd-5e03a6385fea.PNG)

The comparative screenshots between Chrome and Firefox is uploaded [here](https://imgur.com/a/HD4NfgD)

**Comment by raftario** [comment]
Oops, should've catch that one!
